// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoub-iA9pN-riw5mMwYX1FS1DNZhmkanc',
    appId: '1:205779631932:web:20ae2a0eb0a9b08b176839',
    messagingSenderId: '205779631932',
    projectId: 'medical-reminder-app-15d10',
    authDomain: 'medical-reminder-app-15d10.firebaseapp.com',
    storageBucket: 'medical-reminder-app-15d10.firebasestorage.app',
    measurementId: 'G-MZRHWN6D7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3iu8MS7ehvT4qpNcI7x7-PIiyKX3MwGQ',
    appId: '1:205779631932:android:cf3a8ae02963f919176839',
    messagingSenderId: '205779631932',
    projectId: 'medical-reminder-app-15d10',
    storageBucket: 'medical-reminder-app-15d10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcZZQKjG3YrJiXEJRZLtoGvSxjsMh-eQU',
    appId: '1:205779631932:ios:2ece0c7986ba44e4176839',
    messagingSenderId: '205779631932',
    projectId: 'medical-reminder-app-15d10',
    storageBucket: 'medical-reminder-app-15d10.firebasestorage.app',
    iosBundleId: 'com.example.medicalReminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcZZQKjG3YrJiXEJRZLtoGvSxjsMh-eQU',
    appId: '1:205779631932:ios:2ece0c7986ba44e4176839',
    messagingSenderId: '205779631932',
    projectId: 'medical-reminder-app-15d10',
    storageBucket: 'medical-reminder-app-15d10.firebasestorage.app',
    iosBundleId: 'com.example.medicalReminderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoub-iA9pN-riw5mMwYX1FS1DNZhmkanc',
    appId: '1:205779631932:web:2d32c9df7aa69b7d176839',
    messagingSenderId: '205779631932',
    projectId: 'medical-reminder-app-15d10',
    authDomain: 'medical-reminder-app-15d10.firebaseapp.com',
    storageBucket: 'medical-reminder-app-15d10.firebasestorage.app',
    measurementId: 'G-VLDSK8WNPZ',
  );
}
